[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.basedpyright]
typeCheckingMode = "standard"

[project]
name = "gs-tools-py"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = ["pycryptodome"]
